name: Cascade Merge

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [release/0.1, release/0.2]

jobs:
  cascade:
    permissions:
      pull-requests: write
      contents: write
      actions: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for merge history

      # Step 1: Execute the Merge Action (Main Phase)
      # This creates local branches merge/release/1.0/release/1.1 etc.
      - name: Calculate and Merge
        id: cascade
        uses: basilevs/cascade-merge@main # or owner/repo@v1
        with:
          token: ${{ secrets.PAT_TOKEN }} # Use PAT to trigger downstream workflows
          dependency_graph: |
            release/0.1: release/0.2
            release/0.2: main

      # Step 2: Intermediate Actions (Filter unwanted changes)
      # NOTE: If you have multiple downstreams, this script must be smart enough
      # to switch between the branches created by the step above.
      - name: Remove Version Bumps (Intermediate)
        run: |
          # The action sets the last processed branch as active.
          # If we need to process ALL temp branches, we must loop manually.
          # This example assumes the Action outputted the branches or we know logic.
          
          set -xe
          # Example Logic:
          CURRENT_BRANCH=$(git branch --show-current)
          if [[ "$CURRENT_BRANCH" == merge/* ]]; then
             echo "Prevent automatic changes of releng by $CURRENT_BRANCH..."
             git diff --name-only -- 'HEAD^1' | grep pom.xml$ && exit 2 || true
          fi

      # Step 3: The 'Post' phase of the cascade action runs automatically here.
      # It will push the branches and create PRs.