name: Cascade Merge

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [release/0.1, release/0.2]

jobs:
  cascade:
    permissions:
      pull-requests: write
      contents: write
      actions: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0 # Important for merge history

      # Step 1: Execute the Merge Action (Main Phase)
      # This creates local branches merge/release/1.0/release/1.1 etc.
      - name: Merge downstreams and upstream in temporary branches 
        id: cascade
        uses: basilevs/cascade-merge@main # or owner/repo@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use PAT to trigger downstream workflows
          dependency_graph: |
            release/0.1: release/0.2
            release/0.2: main

      # Step 2: Intermediate Actions (Filter unwanted changes)
      # NOTE: If you have multiple downstreams, this script must be smart enough
      # to switch between the branches created by the step above.
      - name: Reject version bumps
        if: ${{ steps.cascade.outputs.target_branches != '' }}
        run: |
          echo "${{ steps.cascade.outputs.target_branches }}" | while read -r downstream; do
            # Skip empty lines if any
            [ -z "$downstream" ] && continue
            
            # Example: Do not merge version bumps automatically
            git checkout -f "origin/$downstream"
            git diff --name-only --merge-base "origin/$downstream" "${{ github.event.workflow_run.head_sha }}" | grep pom.xml$ && exit 2 || true
          done

      # Step 3: The 'Post' phase of the cascade action runs automatically here.
      # It will push the branches and create PRs.