name: Merge downstream

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types: [completed] #requested
    branches: [release/0.1, release/0.2]

env:
  downstream_release/0.1: release/0.2
  downstream_release/0.2: main

run-name: Merge "${{ github.event.workflow_run.display_title }}" from ${{ github.event.workflow_run.head_branch }} downstream 

jobs:
  merge:  
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Merge branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: ${{ github.event.workflow_run.head_branch }}
          target_branch: ${{ env[format('downstream_{0}', github.event.workflow_run.head_branch)] }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Branch of origin
        run: "echo ${{ github.event.workflow_run.head_branch }}"
      - name: Mapping key
        run: "echo ${{ format('downstream_{0}', github.event.workflow_run.head_branch) }} "
      - name: Target branch
        run: "echo ${{ env[format('downstream_{0}', github.event.workflow_run.head_branch)] }}"
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
